name: true_bloc_test
description: A testing library which makes it easy to test true_blocs. Built to be used with the true_bloc state management package.
version: 8.1.0
repository: https://github.com/mit-73/true_bloc/tree/master/packages/true_bloc_test
issue_tracker: https://github.com/mit-73/true_bloc/issues
homepage: https://mit-73.github.io/true_bloc
documentation: https://mit-73.github.io/true_bloc/#/gettingstarted

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  true_bloc:
    path: ../true_bloc

  meta: ^1.3.0
  mocktail: ^0.1.1
  test: ^1.16.0

dev_dependencies:
  pedantic: ^1.10.0
  rxdart: ^0.26.0
