name: true_bloc
description: A predictable state management library that helps implement the true_bloc (Business Logic Component) design pattern.
version: 7.1.0
repository: https://github.com/mit-73/true_bloc/tree/master/packages/true_bloc
issue_tracker: https://github.com/mit-73/true_bloc/issues
homepage: https://github.com/mit-73/true_bloc
documentation: https://mit-73.github.io/true_bloc

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  mocktail: ^0.1.0
  pedantic: ^1.10.0
  rxdart: ^0.26.0
  test: ^1.16.0
