name: replay_true_bloc
description: An extension to the true_bloc state management library which adds support for undo and redo.
version: 0.0.2
repository: https://github.com/mit-73/true_bloc
issue_tracker: https://github.com/mit-73/true_bloc/issues
homepage: https://github.com/mit-73/true_bloc

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  true_bloc:
    path: ../true_bloc

dev_dependencies:
  test: ^1.16.0
