name: flutter_github_search
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  true_bloc:
    path: ../../../packages/true_bloc
  flutter_true_bloc:
    path: ../../../packages/flutter_true_bloc
  url_launcher: ^6.0.0
  common_github_search:
    path: ../common_github_search

dependency_overrides:
  true_bloc:
    path: ../../../packages/true_bloc
  flutter_true_bloc:
    path: ../../../packages/flutter_true_bloc

flutter:
  uses-material-design: true
