name: angular_true_bloc
description: Angular Components that make it easy to implement the true_bloc (Business Logic Component) design pattern. Built to be used with the true_bloc state management package.
version: 7.0.0
repository: https://github.com/mit-73/true_bloc/tree/master/packages/angular_true_bloc
issue_tracker: https://github.com/mit-73/true_bloc/issues
homepage: https://mit-73.github.io/true_bloc
documentation: https://mit-73.github.io/true_bloc/#/gettingstarted

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  angular: ^7.0.0
  true_bloc: ^7.1.0

dev_dependencies:
  angular_test: ^4.0.0
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: ^3.0.0
  meta: ^1.2.3
  mocktail: ^0.1.4
  test: ^1.14.6
