name: flutter_graphql_jobs
description: A example of how to use a GraphQL client with true_bloc.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_true_bloc:
    path: ../../packages/flutter_true_bloc
  graphql: ^3.0.2
  json_annotation: ^3.0.1

dependency_overrides:
  true_bloc:
    path: ../../packages/true_bloc
  flutter_true_bloc:
    path: ../../packages/flutter_true_bloc

dev_dependencies:
  build_runner: ^1.8.1
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
