name: hydrated_true_bloc
description: An extension to the true_bloc state management library which automatically persists and restores true_bloc states.
version: 7.0.1
repository: https://github.com/mit-73/true_bloc
issue_tracker: https://github.com/mit-73/true_bloc/issues
homepage: https://mit-73.github.io/true_bloc
documentation: https://mit-73.github.io/true_bloc/#/gettingstarted

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  true_bloc: ^7.0.0
  hive: ^2.0.0
  meta: ^1.3.0
  synchronized: ^3.0.0

dev_dependencies:
  test: ^1.16.0
  build_runner: ^1.10.0
  collection: ^1.15.0
  crypto: ^3.0.0
  freezed_annotation: ^0.14.0
  freezed: ^0.14.0
  json_serializable: ^4.0.0
  json_annotation: ^4.0.0
  mocktail: ^0.1.0
  path: ^1.8.0
  pedantic: ^1.10.0
  uuid: ^3.0.0
