name: flutter_timer
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  true_bloc:
    path: ../../packages/true_bloc
  flutter_true_bloc:
    path: ../../packages/flutter_true_bloc
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  true_bloc_test: ^8.0.2
  mocktail: ^0.1.4

dependency_overrides:
  true_bloc:
    path: ../../packages/true_bloc
  flutter_true_bloc:
    path: ../../packages/flutter_true_bloc

flutter:
  uses-material-design: true
