name: angular_github_search
description: A web app that uses AngularDart Components

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  angular: ^7.0.0
  true_bloc:
    path: ../../../packages/true_bloc
  angular_true_bloc:
    path: ../../../packages/angular_true_bloc
  common_github_search:
    path: ../common_github_search

dependency_overrides:
  true_bloc:
    path: ../../../packages/true_bloc
  angular_true_bloc:
    path: ../../../packages/angular_true_bloc

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
